MBotRangerCore/MBotRangerCore/Models/ErrorViewModel.cs
using System;

namespace MBotRangerCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MBotRangerCore/MBotRangerCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MBotRangerCore.Models;

namespace MBotRangerCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MBotRangerCore/MBotRangerCore/Controllers/RobotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Net.Sockets;
using System.Net;

namespace MBotRangerCore.Controllers
{
    public class RobotController : Controller
    {
        public byte[] sendbuf;
        public IActionResult Index(string submit)
        {

            switch (submit)
            {
                case "Forward":
                    sendbuf = Encoding.ASCII.GetBytes("1");
                    break;
                case "Back":
                    sendbuf = Encoding.ASCII.GetBytes("2");
                    break;
                case "Go Left":
                    sendbuf = Encoding.ASCII.GetBytes("3");
                    break;
                case "Go Right":
                    sendbuf = Encoding.ASCII.GetBytes("4");
                    break;
                case "Stop":
                    sendbuf = Encoding.ASCII.GetBytes("5");
                    break;
                default:
                    sendbuf = Encoding.ASCII.GetBytes("0");
                    break;
            }

            Socket s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram,
              ProtocolType.Udp);

            IPAddress broadcast = IPAddress.Parse("192.168.4.1");
            IPEndPoint ep = new IPEndPoint(broadcast, 1025);
            s.SendTo(sendbuf, ep);
            return View();
        }


        public ActionResult RobotArrows(int? id)
        {
            ViewData["Key"] = id.ToString();
            sendbuf = Encoding.ASCII.GetBytes(id.ToString());

            Socket s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram,
              ProtocolType.Udp);

            IPAddress broadcast = IPAddress.Parse("192.168.4.1");
            IPEndPoint ep = new IPEndPoint(broadcast, 1025);
            s.SendTo(sendbuf, ep);

            return View();
        }
        public IActionResult Mouse(string submit)
        {

            switch (submit)
            {
                case "Forward":
                    sendbuf = Encoding.ASCII.GetBytes("1");
                    break;
                case "Back":
                    sendbuf = Encoding.ASCII.GetBytes("2");
                    break;
                case "Go Left":
                    sendbuf = Encoding.ASCII.GetBytes("3");
                    break;
                case "Go Right":
                    sendbuf = Encoding.ASCII.GetBytes("4");
                    break;
                case "Stop":
                    sendbuf = Encoding.ASCII.GetBytes("5");
                    break;
                default:
                    sendbuf = Encoding.ASCII.GetBytes("0");
                    break;
            }

            Socket s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram,
              ProtocolType.Udp);

            IPAddress broadcast = IPAddress.Parse("192.168.4.1");
            IPEndPoint ep = new IPEndPoint(broadcast, 1025);
            s.SendTo(sendbuf, ep);
            return View();
        }

    }
}

MBotRangerCore/MBotRangerCore/Controllers/WebcamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MBotRangerCore.Controllers
{
    public class WebcamController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ReloadCam()
        {
            return View("Index");
        }
    }
}

MBotRangerCore/MBotRangerCore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MBotRangerCore/MBotRangerCore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MBotRangerCore/MBotRangerCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MBotRangerCore/MBotRangerCore/Views/Robot/Index.cshtml
@{
    ViewData["Title"] = "Robot Controller";
}

<h2>Control the robot with Buttons</h2>

<link rel="stylesheet" href="~/css/robot.css" />

@using (Html.BeginForm("Index", "Robot"))
{
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

            <input id="forwardBtn" type="submit" name="submit" value="Forward" />

        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <input id="leftBtn" type="submit" name="submit" value="Go Left" />

        </div>
        <div class="col-md-2">

            <input id="stopBtn" type="submit" name="submit" value="Stop" />

        </div>

        <div class="col-md-2">

            <input id="rightBtn" type="submit" name="submit" value="Go Right" />

        </div>

    </div>

    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

            <input id="backBtn" type="submit" name="submit" value="Back" />

        </div>
    </div>

}

MBotRangerCore/MBotRangerCore/Views/Robot/Mouse.cshtml
@{
    ViewData["Title"] = "Mouse";
}

<h2>Mouse</h2>
<link rel="stylesheet" href="~/css/robot.css" />
<!-- 5 Buttons to control the robot-->
@using (Html.BeginForm("Mouse", "Robot"))
{



    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

            <input id="forwardBtn" type="submit" name="submit" value="Forward" />

        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <input id="leftBtn" type="submit" name="submit" value="Go Left" />

        </div>
        <div class="col-md-2">

            <input id="stopBtn" type="submit" name="submit" value="Stop" />

        </div>

        <div class="col-md-2">

            <input id="rightBtn" type="submit" name="submit" value="Go Right" />

        </div>

    </div>

    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

            <input id="backBtn" type="submit" name="submit" value="Back" />

        </div>
    </div>
    <script>
        //Forward button
        document.getElementById("forwardBtn").addEventListener("mousedown", ff);
        document.getElementById("forwardBtn").addEventListener("mouseup", mouseUp);
        document.getElementById("forwardBtn").addEventListener("dblclick", ff);
        function ff() {
            Document(this.click(this.value = 'Forward'));

        }
        //Back button
        document.getElementById("backBtn").addEventListener("mousedown", bb);
        document.getElementById("backBtn").addEventListener("mouseup", mouseUp);
        document.getElementById("backBtn").addEventListener("dblclick", bb);
        //Right button
        document.getElementById("rightBtn").addEventListener("mousedown", rr);
        document.getElementById("rightBtn").addEventListener("mouseup", mouseUp);
        document.getElementById("rightBtn").addEventListener("dblclick", rr);
        //Left button
        document.getElementById("leftBtn").addEventListener("mousedown", ll);
        document.getElementById("leftBtn").addEventListener("mouseup", mouseUp);
        document.getElementById("leftBtn").addEventListener("dd", ll);


        function bb() {
            Document(this.click(this.value='Back'));
        }
        function rr() {
            Document(this.click(this.value = 'Go Right'));
        }
        function ll() {
            Document(this.click(this.value = 'Go Left'));
        }
        function mouseUp() {
            Document(this.click(this.value='Stop'));
        }



    </script>
}

MBotRangerCore/MBotRangerCore/Views/Robot/RobotArrows.cshtml
@{
    ViewData["Title"] = "RobotArrows";
}
<h2>Control the robot using Arrow Keys</h2>
<h4>@ViewData["Key"]</h4>

@section Scripts
{
    <script src="~/js/RobotArrowsNavigation.js"></script>
    <link rel="stylesheet" href="~/css/robot.css" />
}

MBotRangerCore/MBotRangerCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MBotRangerCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Robot" asp-action="Index" class="navbar-brand">Mbot Controller</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  @**  <li><a asp-area="" asp-controller="Robot" asp-action="Index">Robot Buttons</a></li> *@
                    <li><a asp-area="" asp-controller="Webcam" asp-action="Index">Web Cam</a></li>
                    <li><a asp-area="" asp-controller="Robot" asp-action="RobotArrows">Robot Arrows</a></li>
                    <li><a asp-area="" asp-controller="Robot" asp-action="Mouse">Mouse Control</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Integrify</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MBotRangerCore/MBotRangerCore/Views/Webcam/Index.cshtml
@{
    ViewData["Title"] = "Webcam";
}

<p><h2>Webcam page: </h2><b> Displaying a video from a laptop webcam and capturing a photo</b></p>

@section Scripts
    {
    <script src="~/js/WebCamStart.js"></script>
    <link rel="stylesheet" href="~/css/robot.css" />
}
<div class="row">
    @*The appropriate width and height should be 640 and 480 respectively
        canvas size on js file should be the same with cshtml file to avoid croping*@
    <div class="col-md-6">
        <video id="video" width="500" height="330" autoplay></video>
    </div>
    <div class="col-md-6">
        <canvas id="canvas" width="500" height="330"></canvas>
    </div>
</div>

<div class="row">

    <div class="col-md-2">
        <button id="webcam">Start Webcam</button>
    </div>

    <div class="col-md-2">
        <button id="stop">Stop Webcam</button>
    </div>


    <div class="col-md-2">
        <button id="capture">Capture Photo</button>
    </div>

    @*Reloads the webcam page*@

    <div class="col-md-6">
        @using (Html.BeginForm("ReloadCam", "Webcam"))
        {
            <input id="buttonWebcam" type="submit" name="reload" value="Reload" />

        }
    </div>


</div>